language: csharp
solution: SectorFileCompiler.sln

os:
  - linux
  - osx

jobs:
  include:
    - dotnet: latest
      mono: none
    - mono: latest


install:
  - nuget restore SectorFileCompiler.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Release SectorFileCompiler.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./tests/CompilerTest/bin/Release/CompilerTest.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./tests/CompilerCliTest/bin/Release/CompilerCliTest.dll