language: csharp
solution: SectorFileCompiler.sln

branches:
  only:
    - master

jobs:
  include:
    - os: linux 
      dotnet: 3.0.100
      mono: none
    - os: osx
      dotnet: 3.0.100
      mono: none

install:
  - dotnet restore SectorFileCompiler.sln --packages packages

script:
  - dotnet build /p:Configuration=Release SectorFileCompiler.sln --nologo --no-restore /warnaserror || travis_terminate 1;
  - dotnet test tests/CompilerTest/CompilerTest.csproj
  - dotnet test tests/CompilerCliTest/CompilerCliTest.csproj
