language: csharp
solution: SectorFileCompiler.sln

branches:
  only:
    - master

jobs:
  include:
    - os: linux 
      dotnet: 3.0.100
      mono: none
    - os: osx
      dotnet: 3.0.100
      mono: none

install:
  - dotnet restore SectorFileCompiler.sln --packages packages

script:
  - msbuild /p:Configuration=Release SectorFileCompiler.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./tests/CompilerTest/bin/Release/CompilerTest.dll
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./tests/CompilerCliTest/bin/Release/CompilerCliTest.dll
