language: csharp
solution: SectorFileCompiler.sln

branches:
  only:
    - master

jobs:
  include:
    - os: linux 
      mono: none
      dotnet: 3.0.100
    - os: osx
      mono: none
      dotnet: 3.0.100
    - os: linux 
      mono: latest
    - os: osx 
      mono: latest

install:
  - dotnet install xunit.runners -Version 2.4.1 -OutputDirectory testrunner
  - dotnet restore SectorFileCompiler.sln

script:
  - msbuild /p:Configuration=Release SectorFileCompiler.sln
  - mono ./testrunner/xunit.runners.2.4.1/tools/xunit.console.clr4.exe ./tests/CompilerTest/bin/Release/CompilerTest.dll
  - mono ./testrunner/xunit.runners.2.4.1/tools/xunit.console.clr4.exe ./tests/CompilerCliTest/bin/Release/CompilerCliTest.dll