language: csharp
solution: SectorFileCompiler.sln

branches:
  only:
    - master

jobs:
  include:
    - os: linux 
      dotnet: 3.0.100
      mono: none
    - os: osx
      dotnet: 3.0.100
      mono: none

install:
  - dotnet restore SectorFileCompiler.sln --packages packages

script:
  - dotnet build /p:Configuration=Release SectorFileCompiler.sln
  - dotnet test tests/CompilerTest
  - dotnet test tests/CompilerCliTest
