name: Build and Test

on:
  push:
    branches:
      - '*'
      - '**'
  pull_request:

jobs:
  Build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Restore Nuget Packages
        run: dotnet restore SectorFileCompiler.sln --packages packages

      - name: Run Build
        run: dotnet build /p:Configuration=Debug SectorFileCompiler.sln --nologo --no-restore /warnaserror;

      - name: Run Compiler Tests
        if: matrix.platform != 'windows-latest'
        run: dotnet test tests/CompilerTest/CompilerTest.csproj

      - name: Run Compiler Tests With Coverage
        if: matrix.platform == 'windows-latest'
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover tests/CompilerTest/CompilerTest.csproj

      - name: Run Compiler CLI Tests
        if: matrix.platform != 'windows-latest'
        run: dotnet test tests/CompilerCliTest/CompilerCliTest.csproj

      - name: Run Compiler CLI Tests With Coverage
        if: matrix.platform == 'windows-latest'
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover tests/CompilerCliTest/CompilerCliTest.csproj